-- =============================================================================
-- เพิ่ม template ลงตาราง templates (Contact Card + TII Card)
-- รัน: psql -U user -d dbname -f database/seed-templates.sql
-- หรือใน pgAdmin: Query Tool -> เปิดไฟล์นี้ -> F5
-- =============================================================================
-- หมายเหตุ: รันหลัง schema-full.sql และรันครั้งเดียว (ถ้ารันซ้ำจะได้ template ซ้ำชื่อ)
-- =============================================================================

INSERT INTO templates (name, description, template_json, preview_image)
SELECT 'Contact Card', 'Template สำหรับการ์ดข้อมูลติดต่อ (Carousel - 2 cards)', $json${"tectony1":[{"linemsg":"การ์ดข้อมูลติดต่อของ {name}"},{"type":"carousel","contents":[{"type":"bubble","hero":{"type":"image","url":"{user_image1}","size":"full","aspectMode":"cover"},"body":{"type":"box","layout":"vertical","contents":[{"type":"text","text":"{name}","weight":"bold","size":"xl","color":"#1DB446"},{"type":"separator","margin":"md"},{"type":"box","layout":"horizontal","margin":"md","contents":[{"type":"text","text":"Tel.","size":"sm","color":"#aaaaaa","flex":0},{"type":"text","text":"{phone}","size":"sm","color":"#666666","flex":1,"wrap":true,"margin":"md"}]},{"type":"box","layout":"horizontal","margin":"md","contents":[{"type":"text","text":"Email","size":"sm","color":"#aaaaaa","flex":0},{"type":"text","text":"{email}","size":"sm","color":"#666666","flex":1,"wrap":true,"margin":"md"}]},{"type":"separator","margin":"md"},{"type":"text","text":"รายละเอียด","size":"sm","color":"#1DB446","weight":"bold","margin":"md"},{"type":"text","text":"{description}","size":"sm","color":"#666666","margin":"sm","wrap":true}]},"footer":{"type":"box","layout":"vertical","contents":[{"type":"box","layout":"horizontal","contents":[{"type":"button","style":"primary","action":{"type":"uri","label":"โทร","uri":"tel:{phone}"}},{"type":"button","style":"secondary","action":{"type":"uri","label":"ส่งอีเมล","uri":"mailto:{email}"}}]},{"type":"box","layout":"horizontal","contents":[{"type":"button","style":"link","action":{"type":"uri","label":"แชร์","uri":"{liff_url}"}}]}]}},{"type":"bubble","hero":{"type":"image","url":"{user_image1}","size":"full","aspectMode":"cover"},"body":{"type":"box","layout":"vertical","contents":[{"type":"text","text":"{description2}","weight":"bold","size":"lg","align":"center","wrap":true,"color":"#333333"}]}}]}]}$json$, '/images/template-preview.jpg'
WHERE NOT EXISTS (SELECT 1 FROM templates WHERE name = 'Contact Card');

INSERT INTO templates (name, description, template_json, preview_image)
SELECT 'TII Card', 'Template TII Card (Carousel 2 การ์ด: ข้อมูลติดต่อ + แบนเนอร์)', $json${"tectony1":[{"linemsg":"การ์ดของ {name}"},{"type":"carousel","contents":[{"type":"bubble","hero":{"type":"image","url":"{image_url1}","aspectMode":"cover","size":"full"},"body":{"type":"box","layout":"vertical","contents":[{"type":"box","layout":"vertical","contents":[{"type":"text","text":"{name}","align":"center","wrap":true,"size":"lg"}]},{"type":"separator","margin":"md"},{"type":"box","layout":"horizontal","contents":[{"type":"text","text":"📞","flex":0},{"type":"text","text":"{phone}","margin":"xs","wrap":true}],"spacing":"none","margin":"md"},{"type":"box","layout":"horizontal","contents":[{"type":"text","text":"📧","flex":0},{"type":"text","text":"{email}","margin":"xs","wrap":true}],"margin":"sm"},{"type":"separator","margin":"md"},{"type":"box","layout":"horizontal","contents":[{"type":"text","text":"💬","flex":0},{"type":"text","text":"{description}","wrap":true,"margin":"sm"}],"margin":"md"},{"type":"separator","margin":"md"}]},"footer":{"type":"box","layout":"vertical","contents":[{"type":"box","layout":"horizontal","contents":[{"type":"button","action":{"type":"uri","label":"โทร.","uri":"tel:{phone}"},"style":"primary","height":"sm","color":"#2ECC71"},{"type":"button","action":{"type":"uri","label":"ส่งเมล","uri":"mailto:{email}"},"style":"primary","height":"sm","color":"#F39C12"},{"type":"button","action":{"type":"uri","label":"แชร์","uri":"{liff_url}"},"style":"primary","height":"sm","color":"#3498DB"}],"spacing":"sm"}]}},{"type":"bubble","hero":{"type":"image","url":"https://www.innwhy.com/wp-content/uploads/2019/01/Tii-Ads-banner-01.png","aspectMode":"fit","size":"full"},"body":{"type":"box","layout":"vertical","contents":[]},"styles":{"hero":{"backgroundColor":"#14256B"},"body":{"backgroundColor":"#14256B"},"footer":{"backgroundColor":"#14256B"}}}]}]}$json$, 'https://www.innwhy.com/wp-content/uploads/2019/01/Tii-Ads-banner-01.png'
WHERE NOT EXISTS (SELECT 1 FROM templates WHERE name = 'TII Card');
